# Generated by Django 3.2.25 on 2024-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_del_veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.CharField(max_length=20)),
                ('Fecha', models.DateField()),
                ('Proyecto', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Partes_a_inspeccionar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.BooleanField(default=False)),
                ('nc', models.BooleanField(default=False)),
                ('na', models.ImageField(upload_to='')),
            ],
        ),
    ]
