# Generated by Django 3.2.25 on 2024-06-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpart',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
