# Generated by Django 5.1 on 2024-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Labrado_de_las_llantas_delanteras_NC',
            field=models.ImageField(upload_to='Labrado de las llantas delanteras'),
        ),
        migrations.AlterField(
            model_name='images',
            name='Nivel_aceite_NC',
            field=models.ImageField(upload_to='Nivel de aceite'),
        ),
        migrations.AlterField(
            model_name='images',
            name='aire_acondicionado_NC',
            field=models.ImageField(upload_to='Aire acondicionado'),
        ),
        migrations.AlterField(
            model_name='images',
            name='bornes_baterias_ajustados_NC',
            field=models.ImageField(upload_to='Bornes baterias ajustados'),
        ),
        migrations.AlterField(
            model_name='images',
            name='botiquin_primeros_auxilios_NC',
            field=models.ImageField(upload_to='Botiquin primeros auxilios'),
        ),
        migrations.AlterField(
            model_name='images',
            name='capot_asegurado_NC',
            field=models.ImageField(upload_to='Capot asegurado'),
        ),
        migrations.AlterField(
            model_name='images',
            name='carroceria_buen_estado_NC',
            field=models.ImageField(upload_to='carroceria en buen estado'),
        ),
        migrations.AlterField(
            model_name='images',
            name='cinturones_seguridad_NC',
            field=models.ImageField(upload_to='Cinturones seguridad'),
        ),
        migrations.AlterField(
            model_name='images',
            name='direccionales_funcionando_NC',
            field=models.ImageField(upload_to='direccionales funcionando'),
        ),
        migrations.AlterField(
            model_name='images',
            name='equipo_prevencion_seguridad_NC',
            field=models.ImageField(upload_to='Equipo prevencion seguridad'),
        ),
        migrations.AlterField(
            model_name='images',
            name='espejo_exterior_buen_estado_NC',
            field=models.ImageField(upload_to='espejo exterior buen estado'),
        ),
        migrations.AlterField(
            model_name='images',
            name='extintor_NC',
            field=models.ImageField(upload_to='Extintor'),
        ),
        migrations.AlterField(
            model_name='images',
            name='freno_estacionamiento_NC',
            field=models.ImageField(upload_to='Freno estacionamiento'),
        ),
        migrations.AlterField(
            model_name='images',
            name='funcionamiento_luces_delanteras_NC',
            field=models.ImageField(upload_to='funcionamiento de luces delanteras'),
        ),
        migrations.AlterField(
            model_name='images',
            name='indicadores_tablero_control_NC',
            field=models.ImageField(upload_to='Indicadores tablero control'),
        ),
        migrations.AlterField(
            model_name='images',
            name='kit_carreteras_NC',
            field=models.ImageField(upload_to='Kit carreteras'),
        ),
        migrations.AlterField(
            model_name='images',
            name='labrado_llanta_repuesto_NC',
            field=models.ImageField(upload_to='labrado de la llanta repuesto'),
        ),
        migrations.AlterField(
            model_name='images',
            name='labrado_llantas_traseras_NC',
            field=models.ImageField(upload_to='labrado de las llantas traseras'),
        ),
        migrations.AlterField(
            model_name='images',
            name='limpiaparabrisas_NC',
            field=models.ImageField(upload_to='Limpiaparabrisas'),
        ),
        migrations.AlterField(
            model_name='images',
            name='luces_traseras_funcionando_NC',
            field=models.ImageField(upload_to='luces traseras funcionando'),
        ),
        migrations.AlterField(
            model_name='images',
            name='pito_electrico_NC',
            field=models.ImageField(upload_to='Pito electrico'),
        ),
        migrations.AlterField(
            model_name='images',
            name='placa_delantera_legible_NC',
            field=models.ImageField(upload_to='placa delantera legible'),
        ),
        migrations.AlterField(
            model_name='images',
            name='placa_trasera_legible_NC',
            field=models.ImageField(upload_to='placa trasera legible'),
        ),
        migrations.AlterField(
            model_name='images',
            name='sensor_externo_velocidad_NC',
            field=models.ImageField(upload_to='Sensor externo velocidad'),
        ),
        migrations.AlterField(
            model_name='images',
            name='sin_fugas_tanque_combustible',
            field=models.ImageField(upload_to='sin fugas tanque combustible'),
        ),
        migrations.AlterField(
            model_name='images',
            name='sonido_alarma_reversa_NC',
            field=models.ImageField(upload_to='sonido alarma reversa'),
        ),
        migrations.AlterField(
            model_name='images',
            name='vidrio_delantero_sin_fisuras_NC',
            field=models.ImageField(upload_to='vidrio delantero sin fisuras'),
        ),
        migrations.AlterField(
            model_name='images',
            name='vidrios_laterales_sin_fisuras_NC',
            field=models.ImageField(upload_to='vidrios laterales sin fisuras'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='Nivel_del_combustible',
            field=models.ImageField(upload_to='Nivel gasometro'),
        ),
    ]
