# Generated by Django 3.2.25 on 2024-04-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costado',
        ),
        migrations.DeleteModel(
            name='ParteDelantera',
        ),
        migrations.DeleteModel(
            name='ParteTrasera',
        ),
    ]
