# Generated by Django 3.2.25 on 2024-04-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos_del_veiculo',
            new_name='Datos_generales',
        ),
    ]
