# Generated by Django 3.2.25 on 2024-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='Fecha_emicion_de_revision_tecnomecanica',
            field=models.DateField(null=True),
        ),
    ]
