# Generated by Django 3.2.25 on 2024-04-11 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0002_rename_datos_del_veiculo_datos_generales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carroceria_buen_estado', models.BooleanField(default=False)),
                ('vidrios_laterales_sin_fisuras', models.BooleanField(default=False)),
                ('direccionales_funcionando', models.BooleanField(default=False)),
                ('espejo_exterior_buen_estado', models.BooleanField(default=False)),
                ('sin_fugas_tanque_combustible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParteDelantera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionamiento_luces_delanteras', models.BooleanField(default=False)),
                ('vidrio_delantero_sin_fisuras', models.BooleanField(default=False)),
                ('placa_delantera_legible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParteTrasera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luces_traseras_funcionando', models.BooleanField(default=False)),
                ('sonido_alarma_reversa', models.BooleanField(default=False)),
                ('labrado_llantas_traseras', models.BooleanField(default=False)),
                ('labrado_llanta_repuesto', models.BooleanField(default=False)),
                ('placa_trasera_legible', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='datos_generales',
            old_name='Name',
            new_name='Nombre',
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='Fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nivel_aceite_operacional', models.BooleanField(default=False)),
                ('capot_asegurado', models.BooleanField(default=False)),
                ('bornes_baterias_ajustados', models.BooleanField(default=False)),
                ('indicadores_tablero_control', models.BooleanField(default=False)),
                ('kilometraje_inicial', models.IntegerField(default=0)),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('freno_estacionamiento', models.BooleanField(default=False)),
                ('limpiaparabrisas', models.BooleanField(default=False)),
                ('pito_electrico', models.BooleanField(default=False)),
                ('cinturones_seguridad', models.BooleanField(default=False)),
                ('equipo_prevencion_seguridad', models.BooleanField(default=False)),
                ('botiquin_primeros_auxilios', models.BooleanField(default=False)),
                ('extintor', models.BooleanField(default=False)),
                ('kit_carreteras', models.BooleanField(default=False)),
                ('sensor_externo_velocidad', models.BooleanField(default=False)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preoperacional_app.datos_generales')),
            ],
        ),
    ]
