# Generated by Django 5.1 on 2024-08-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0002_alter_images_labrado_de_las_llantas_delanteras_nc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ED_LI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Aid_Kit_LI', models.DateField()),
                ('Fire_Extinguisher_ED', models.DateField()),
                ('Spill_Kit_LI', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='kit_carreteras',
            new_name='kit_derrames',
        ),
    ]
