# Generated by Django 3.2.25 on 2024-05-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0002_alter_vehiculo_fecha_emicion_de_revision_tecnomecanica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Fecha_emicion_SOAT',
            new_name='Fecha_vencimiento_SOAT',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Fecha_emicion_poliza',
            new_name='Fecha_vencimiento_poliza',
        ),
    ]
