# Generated by Django 3.2.25 on 2024-06-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0002_backpart_observaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backpart',
            old_name='observaciones',
            new_name='Obser',
        ),
    ]
