# Generated by Django 5.1 on 2024-08-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0003_ed_li_rename_kit_carreteras_inspeccion_kit_derrames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_generales',
            name='Proyecto',
            field=models.CharField(max_length=18),
        ),
    ]
