# Generated by Django 3.2.25 on 2024-04-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0003_auto_20240411_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccion',
            old_name='aire_acondicionado',
            new_name='aire_acondicionado_C',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='bornes_baterias_ajustados',
            new_name='aire_acondicionado_NA',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='botiquin_primeros_auxilios',
            new_name='bornes_baterias_ajustados_C',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='capot_asegurado',
            new_name='bornes_baterias_ajustados_NA',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='cinturones_seguridad',
            new_name='botiquin_primeros_auxilios_C',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='equipo_prevencion_seguridad',
            new_name='botiquin_primeros_auxilios_NA',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='extintor',
            new_name='capot_asegurado_C',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='freno_estacionamiento',
            new_name='capot_asegurado_NA',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='indicadores_tablero_control',
            new_name='cinturones_seguridad_C',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='kit_carreteras',
            new_name='cinturones_seguridad_NA',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='limpiaparabrisas',
            new_name='equipo_prevencion_seguridad_C',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='nivel_aceite_operacional',
            new_name='equipo_prevencion_seguridad_NA',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='pito_electrico',
            new_name='extintor_C',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='sensor_externo_velocidad',
            new_name='extintor_NA',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='kilometraje_inicial',
            new_name='kilometraje_inicial_C',
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='aire_acondicionado_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='bornes_baterias_ajustados_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='botiquin_primeros_auxilios_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='capot_asegurado_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='cinturones_seguridad_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='equipo_prevencion_seguridad_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='extintor_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='freno_estacionamiento_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='freno_estacionamiento_NA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='freno_estacionamiento_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='indicadores_tablero_control_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='indicadores_tablero_control_NA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='indicadores_tablero_control_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='kilometraje_inicial_NA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='kilometraje_inicial_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='kit_carreteras_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='kit_carreteras_NA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='kit_carreteras_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='limpiaparabrisas_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='limpiaparabrisas_NA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='limpiaparabrisas_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='nivel_aceite_operacional_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='nivel_aceite_operacional_NA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='nivel_aceite_operacional_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='pito_electrico_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='pito_electrico_NA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='pito_electrico_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='sensor_externo_velocidad_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='sensor_externo_velocidad_NA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='sensor_externo_velocidad_NC',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
