# Generated by Django 3.2.25 on 2024-05-07 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0003_auto_20240507_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='Fecha_emicion_de_revision_tecnomecanica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='Fecha_vencimiento_SOAT',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='Fecha_vencimiento_poliza',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
