# Generated by Django 3.2.25 on 2024-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0004_auto_20240420_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='aire_acondicionado',
            field=models.CharField(default='No Data', max_length=250),
        ),
    ]
