# Generated by Django 3.2.25 on 2024-05-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0004_auto_20240507_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccion',
            old_name='Nivel_gasometro',
            new_name='Nivel_del_combustible',
        ),
    ]
