# Generated by Django 5.1 on 2024-09-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0004_alter_datos_generales_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='Nivel_aceite',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='aire_acondicionado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='bornes_baterias_ajustados',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='botiquin_primeros_auxilios',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='capot_asegurado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='cinturones_seguridad',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='equipo_prevencion_seguridad',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='extintor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='freno_estacionamiento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='indicadores_tablero_control',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='kit_derrames',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='limpiaparabrisas',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='pito_electrico',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='sensor_externo_velocidad',
            field=models.CharField(max_length=10),
        ),
    ]
