# Generated by Django 3.2.25 on 2024-04-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0004_auto_20240412_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccion',
            old_name='aire_acondicionado_C',
            new_name='aire_acondicionado',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='bornes_baterias_ajustados_C',
            new_name='bornes_baterias_ajustados',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='botiquin_primeros_auxilios_C',
            new_name='botiquin_primeros_auxilios',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='capot_asegurado_C',
            new_name='capot_asegurado',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='cinturones_seguridad_C',
            new_name='cinturones_seguridad',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='equipo_prevencion_seguridad_C',
            new_name='equipo_prevencion_seguridad',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='extintor_C',
            new_name='extintor',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='freno_estacionamiento_C',
            new_name='freno_estacionamiento',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='indicadores_tablero_control_C',
            new_name='indicadores_tablero_control',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='kilometraje_inicial_C',
            new_name='kilometraje_inicial',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='kit_carreteras_C',
            new_name='kit_carreteras',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='limpiaparabrisas_C',
            new_name='limpiaparabrisas',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='nivel_aceite_operacional_C',
            new_name='nivel_aceite_operacional',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='pito_electrico_C',
            new_name='pito_electrico',
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='sensor_externo_velocidad_C',
            new_name='sensor_externo_velocidad',
        ),
    ]
