# Generated by Django 3.2.25 on 2024-04-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0006_auto_20240412_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='datos_generales',
            name='Placa',
        ),
        migrations.AddField(
            model_name='partedelantera',
            name='Labrado_de_las_llantas_delanteras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partedelantera',
            name='Labrado_de_las_llantas_delanteras_NA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partedelantera',
            name='Labrado_de_las_llantas_delanteras_NC',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preoperacional_app.vehiculo'),
        ),
    ]
