# Generated by Django 5.1 on 2024-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0006_alter_ed_li_fire_extinguisher_ed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ed_li',
            name='Fire_Extinguisher_ED',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ed_li',
            name='First_Aid_Kit_LI',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ed_li',
            name='Spill_Kit_LI',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='aire_acondicionado',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='bornes_baterias_ajustados',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='botiquin_primeros_auxilios',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='cinturones_seguridad',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='equipo_prevencion_seguridad',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='extintor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='freno_estacionamiento',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='indicadores_tablero_control',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='kit_derrames',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='limpiaparabrisas',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='pito_electrico',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='sensor_externo_velocidad',
            field=models.CharField(max_length=250),
        ),
    ]
