# Generated by Django 3.2.25 on 2024-04-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0007_auto_20240412_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='Nivel_gasometro',
            field=models.ImageField(default=False, upload_to='Nivel gasometro'),
        ),
    ]
