# Generated by Django 5.1 on 2024-09-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0008_alter_backpart_labrado_llanta_repuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ed_li',
            name='Fire_Extinguisher_ED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ed_li',
            name='First_Aid_Kit_LI',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ed_li',
            name='Spill_Kit_LI',
            field=models.DateField(blank=True, null=True),
        ),
    ]
