# Generated by Django 3.2.25 on 2024-04-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0008_inspeccion_nivel_gasometro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='kilometraje_inicial_NA',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='kilometraje_inicial_NC',
        ),
    ]
