# Generated by Django 3.2.25 on 2024-04-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0008_alter_inspeccion_aire_acondicionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='datos_generales',
            name='vehiculo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Preoperacional_app.vehiculo'),
            preserve_default=False,
        ),
    ]
