# Generated by Django 5.1 on 2024-09-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0009_alter_ed_li_fire_extinguisher_ed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_generales',
            name='Destino',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_generales',
            name='Origen',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
