# Generated by Django 3.2.25 on 2024-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0009_auto_20240413_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costado',
            name='carroceria_buen_estado_NC',
            field=models.ImageField(default=False, upload_to='carroceria en buen estado'),
        ),
        migrations.AlterField(
            model_name='costado',
            name='direccionales_funcionando_NC',
            field=models.ImageField(default=False, upload_to='direccionales funcionando'),
        ),
        migrations.AlterField(
            model_name='costado',
            name='espejo_exterior_buen_estado_NC',
            field=models.ImageField(default=False, upload_to='espejo exterior buen estado'),
        ),
        migrations.AlterField(
            model_name='costado',
            name='sin_fugas_tanque_combustible_NC',
            field=models.ImageField(default=False, upload_to='sin fugas en el tanque combustible'),
        ),
        migrations.AlterField(
            model_name='costado',
            name='vidrios_laterales_sin_fisuras_NC',
            field=models.ImageField(default=False, upload_to='vidrios laterales sin fisuras'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='aire_acondicionado_NC',
            field=models.ImageField(default=False, upload_to='correcto funcionamiento del aire acondicionado'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='bornes_baterias_ajustados_NC',
            field=models.ImageField(default=False, upload_to='bornes de baterias ajustados'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='botiquin_primeros_auxilios_NC',
            field=models.ImageField(default=False, upload_to='botiquin de primeros auxilios'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='capot_asegurado_NC',
            field=models.ImageField(default=False, upload_to='capot asegurado'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='cinturones_seguridad_NC',
            field=models.ImageField(default=False, upload_to='correcto funcionamiento de los cinturones seguridad'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='equipo_prevencion_seguridad_NC',
            field=models.ImageField(default=False, upload_to='equipo de prevencion y seguridad'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='extintor_NC',
            field=models.ImageField(default=False, upload_to='extintor'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='freno_estacionamiento_NC',
            field=models.ImageField(default=False, upload_to='correcto funcionamiento del freno estacionamiento'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='indicadores_tablero_control_NC',
            field=models.ImageField(default=False, upload_to='correcto funcionamiento de los indicadores de tablero control'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='kit_carreteras_NC',
            field=models.ImageField(default=False, upload_to='kit de carreteras'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='limpiaparabrisas_NC',
            field=models.ImageField(default=False, upload_to='correcto funcionamiento del limpiaparabrisas'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='nivel_aceite_operacional_NC',
            field=models.ImageField(default=False, upload_to='nivel de aceite operacional'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='pito_electrico_NC',
            field=models.ImageField(default=False, upload_to='correcto funcionamiento del pito electrico'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='sensor_externo_velocidad_NC',
            field=models.ImageField(default=False, upload_to='sensor externo de velocidad'),
        ),
        migrations.AlterField(
            model_name='partedelantera',
            name='Labrado_de_las_llantas_delanteras_NC',
            field=models.ImageField(default=False, upload_to='Labrado de las llantas delanteras'),
        ),
        migrations.AlterField(
            model_name='partedelantera',
            name='funcionamiento_luces_delanteras_NC',
            field=models.ImageField(default=False, upload_to='funcionamiento de luces delanteras'),
        ),
        migrations.AlterField(
            model_name='partedelantera',
            name='placa_delantera_legible_NC',
            field=models.ImageField(default=False, upload_to='placa delantera legible'),
        ),
        migrations.AlterField(
            model_name='partedelantera',
            name='vidrio_delantero_sin_fisuras_NC',
            field=models.ImageField(default=False, upload_to='vidrio delantero sin fisuras'),
        ),
        migrations.AlterField(
            model_name='partetrasera',
            name='labrado_llanta_repuesto_NC',
            field=models.ImageField(default=False, upload_to='labrado de la llanta repuesto'),
        ),
        migrations.AlterField(
            model_name='partetrasera',
            name='labrado_llantas_traseras_NC',
            field=models.ImageField(default=False, upload_to='labrado de las llantas traseras'),
        ),
        migrations.AlterField(
            model_name='partetrasera',
            name='luces_traseras_funcionando_NC',
            field=models.ImageField(default=False, upload_to='luces traseras funcionando'),
        ),
        migrations.AlterField(
            model_name='partetrasera',
            name='placa_trasera_legible_NC',
            field=models.ImageField(default=False, upload_to='placa trasera legible'),
        ),
        migrations.AlterField(
            model_name='partetrasera',
            name='sonido_alarma_reversa_NC',
            field=models.ImageField(default=False, upload_to='sonido alarma reversa'),
        ),
    ]
