# Generated by Django 3.2.25 on 2024-04-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0009_auto_20240420_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luces_traseras_funcionando', models.CharField(max_length=250)),
                ('sonido_alarma_reversa', models.CharField(max_length=250)),
                ('labrado_llantas_traseras', models.CharField(max_length=250)),
                ('labrado_llanta_repuesto', models.CharField(max_length=250)),
                ('placa_trasera_legible', models.CharField(max_length=250)),
                ('luces_traseras_funcionando_NC', models.ImageField(default=False, upload_to='luces traseras funcionando')),
                ('sonido_alarma_reversa_NC', models.ImageField(default=False, upload_to='sonido alarma reversa')),
                ('labrado_llantas_traseras_NC', models.ImageField(default=False, upload_to='labrado de las llantas traseras')),
                ('labrado_llanta_repuesto_NC', models.ImageField(default=False, upload_to='labrado de la llanta repuesto')),
                ('placa_trasera_legible_NC', models.ImageField(default=False, upload_to='placa trasera legible')),
            ],
        ),
        migrations.CreateModel(
            name='FrontPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionamiento_luces_delanteras', models.CharField(max_length=250)),
                ('vidrio_delantero_sin_fisuras', models.CharField(max_length=250)),
                ('placa_delantera_legible', models.CharField(max_length=250)),
                ('Labrado_de_las_llantas_delanteras', models.CharField(max_length=250)),
                ('funcionamiento_luces_delanteras_NC', models.ImageField(default=False, upload_to='funcionamiento de luces delanteras')),
                ('vidrio_delantero_sin_fisuras_NC', models.ImageField(default=False, upload_to='vidrio delantero sin fisuras')),
                ('placa_delantera_legible_NC', models.ImageField(default=False, upload_to='placa delantera legible')),
                ('Labrado_de_las_llantas_delanteras_NC', models.ImageField(default=False, upload_to='Labrado de las llantas delanteras')),
            ],
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carroceria_buen_estado', models.CharField(max_length=250)),
                ('vidrios_laterales_sin_fisuras', models.CharField(max_length=250)),
                ('direccionales_funcionando', models.CharField(max_length=250)),
                ('espejo_exterior_buen_estado', models.CharField(max_length=250)),
                ('sin_fugas_tanque_combustible', models.CharField(max_length=250)),
                ('carroceria_buen_estado_NC', models.ImageField(default=False, upload_to='carroceria en buen estado')),
                ('vidrios_laterales_sin_fisuras_NC', models.ImageField(default=False, upload_to='vidrios laterales sin fisuras')),
                ('direccionales_funcionando_NC', models.ImageField(default=False, upload_to='direccionales funcionando')),
                ('espejo_exterior_buen_estado_NC', models.ImageField(default=False, upload_to='espejo exterior buen estado')),
            ],
        ),
    ]
