# Generated by Django 3.2.25 on 2024-04-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0010_backpart_frontpart_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histoial_archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_archivo', models.CharField(max_length=200)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preoperacional_app.vehiculo')),
            ],
        ),
    ]
