# Generated by Django 3.2.25 on 2024-04-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0011_histoial_archivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='histoial_archivos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
