# Generated by Django 3.2.25 on 2024-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0012_histoial_archivos_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel_aceite_NC', models.ImageField(default=False, upload_to='Nivel de aceite')),
                ('bornes_baterias_ajustados_NC', models.ImageField(default=False, upload_to='Bornes baterias ajustados')),
                ('indicadores_tablero_control_NC', models.ImageField(default=False, upload_to='Indicadores tablero control')),
                ('aire_acondicionado_NC', models.ImageField(default=False, upload_to='Aire acondicionado')),
                ('freno_estacionamiento_NC', models.ImageField(default=False, upload_to='Freno estacionamiento')),
                ('limpiaparabrisas_NC', models.ImageField(default=False, upload_to='Limpiaparabrisas')),
                ('pito_electrico_NC', models.ImageField(default=False, upload_to='Pito electrico')),
                ('cinturones_seguridad_NC', models.ImageField(default=False, upload_to='Cinturones seguridad')),
                ('equipo_prevencion_seguridad_NC', models.ImageField(default=False, upload_to='Equipo prevencion seguridad')),
                ('botiquin_primeros_auxilios_NC', models.ImageField(default=False, upload_to='Botiquin primeros auxilios')),
                ('extintor_NC', models.ImageField(default=False, upload_to='Extintor')),
                ('kit_carreteras_NC', models.ImageField(default=False, upload_to='Kit carreteras')),
                ('sensor_externo_velocidad_NC', models.ImageField(default=False, upload_to='Sensor externo velocidad')),
                ('funcionamiento_luces_delanteras_NC', models.ImageField(default=False, upload_to='funcionamiento de luces delanteras')),
                ('vidrio_delantero_sin_fisuras_NC', models.ImageField(default=False, upload_to='vidrio delantero sin fisuras')),
                ('placa_delantera_legible_NC', models.ImageField(default=False, upload_to='placa delantera legible')),
                ('Labrado_de_las_llantas_delanteras_NC', models.ImageField(default=False, upload_to='Labrado de las llantas delanteras')),
                ('carroceria_buen_estado_NC', models.ImageField(default=False, upload_to='carroceria en buen estado')),
                ('vidrios_laterales_sin_fisuras_NC', models.ImageField(default=False, upload_to='vidrios laterales sin fisuras')),
                ('direccionales_funcionando_NC', models.ImageField(default=False, upload_to='direccionales funcionando')),
                ('espejo_exterior_buen_estado_NC', models.ImageField(default=False, upload_to='espejo exterior buen estado')),
                ('luces_traseras_funcionando_NC', models.ImageField(default=False, upload_to='luces traseras funcionando')),
                ('sonido_alarma_reversa_NC', models.ImageField(default=False, upload_to='sonido alarma reversa')),
                ('labrado_llantas_traseras_NC', models.ImageField(default=False, upload_to='labrado de las llantas traseras')),
                ('labrado_llanta_repuesto_NC', models.ImageField(default=False, upload_to='labrado de la llanta repuesto')),
                ('placa_trasera_legible_NC', models.ImageField(default=False, upload_to='placa trasera legible')),
            ],
        ),
        migrations.RemoveField(
            model_name='backpart',
            name='labrado_llanta_repuesto_NC',
        ),
        migrations.RemoveField(
            model_name='backpart',
            name='labrado_llantas_traseras_NC',
        ),
        migrations.RemoveField(
            model_name='backpart',
            name='luces_traseras_funcionando_NC',
        ),
        migrations.RemoveField(
            model_name='backpart',
            name='placa_trasera_legible_NC',
        ),
        migrations.RemoveField(
            model_name='backpart',
            name='sonido_alarma_reversa_NC',
        ),
        migrations.RemoveField(
            model_name='frontpart',
            name='Labrado_de_las_llantas_delanteras_NC',
        ),
        migrations.RemoveField(
            model_name='frontpart',
            name='funcionamiento_luces_delanteras_NC',
        ),
        migrations.RemoveField(
            model_name='frontpart',
            name='placa_delantera_legible_NC',
        ),
        migrations.RemoveField(
            model_name='frontpart',
            name='vidrio_delantero_sin_fisuras_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='Nivel_aceite_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='aire_acondicionado_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='bornes_baterias_ajustados_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='botiquin_primeros_auxilios_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='capot_asegurado_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='cinturones_seguridad_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='equipo_prevencion_seguridad_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='extintor_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='freno_estacionamiento_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='indicadores_tablero_control_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='kit_carreteras_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='limpiaparabrisas_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='pito_electrico_NC',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='sensor_externo_velocidad_NC',
        ),
        migrations.RemoveField(
            model_name='side',
            name='carroceria_buen_estado_NC',
        ),
        migrations.RemoveField(
            model_name='side',
            name='direccionales_funcionando_NC',
        ),
        migrations.RemoveField(
            model_name='side',
            name='espejo_exterior_buen_estado_NC',
        ),
        migrations.RemoveField(
            model_name='side',
            name='vidrios_laterales_sin_fisuras_NC',
        ),
    ]
