# Generated by Django 3.2.25 on 2024-04-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0012_inspeccion_nive_aceite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccion',
            old_name='Nive_aceite',
            new_name='Nivel_aceite',
        ),
    ]
