# Generated by Django 3.2.25 on 2024-04-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0013_auto_20240430_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='capot_asegurado_NC',
            field=models.ImageField(default=False, upload_to='Capot asegurado'),
        ),
    ]
