# Generated by Django 3.2.25 on 2024-04-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0014_inspeccion_nivel_aceite_na'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='Nivel_aceite_NC',
            field=models.ImageField(default=False, upload_to='Nivel de aceite'),
        ),
    ]
