# Generated by Django 3.2.25 on 2024-04-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0014_images_capot_asegurado_nc'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='sin_fugas_tanque_combustible',
            field=models.ImageField(default=False, upload_to='sin fugas tanque combustible'),
        ),
    ]
