# Generated by Django 3.2.25 on 2024-04-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preoperacional_app', '0015_inspeccion_nivel_aceite_nc'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='capot_asegurado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='capot_asegurado_NA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='capot_asegurado_NC',
            field=models.ImageField(default=False, upload_to='Capot_asegurado'),
        ),
    ]
