# Generated by Django 5.1 on 2024-09-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pre_Op_equipos_medicion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinspection',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
