
def Cell_selector ():
    Cell_assignment = {
        "cmc_356_omicron": "H15",
        "cmc_353_omicron": "H16",
        "doble_f6150": "H17",
        "ponovo_l336i": "H18",
        "cpc_100_omicron": "H19",
        "cp_td1_omicron": "H20",
        "cp_cu1_omicron": "H21",
        "cp_cr500_omicron": "H22",
        "ct_analyzer_omicron": "H23",
        "franalizer_omicron": "H24",
        "cp_cb2_omicron": "H25",
        "ponovo_pct_200ai": "H26",
        "factor_hv_hipot_gd6000a": "H27",
        "potencia_tang_delta_avo": "H28",
        "micro_contactos_dmo200": "H29",
        "vacuometro_digital": "H30",
        "calidad_energia_metrel": "R15",
        "tiempos_operacion_gdkc_6a": "R16",
        "tiempos_operacion_egil": "R17",
        "sata40_tension_minima": "R18",
        "relacion_trans_ttr_gbii": "R19",
        "r_devanados_hv_gdzrs_20a": "R20",
        "r_devanados_hv_gdzrc_5a": "R21",
        "milliohm_sonel": "R22",
        "medidor_mit520_megger": "R23",
        "medidor_mit500_megger": "R24",
        "medidor_mic_5010_sonel": "R25",
        "medidor_mic_5015_sonel": "R26",
        "medidor_mic_5010_sonel_25kv": "R27",
        "medidor_mic_5005_sonel": "R28",
        "telurometro_metrotech": "R29",
        "chisporroteo_megger_ots60bp": "R30",
        "circuito_mpc_5_5_50": "AB16",
        "probador_cts_cct_xsaid": "AB15",
        "vaisala_punto_rocio": "AB17",
        "recuperador_gas_sf6_gr": "AB18",
        "recuperador_gas_sf6_pe": "AB19",
        "bomba_vacio_sf6": "AB20",
        "analizador_gas_sf6_grande": "AB21",
        "analizador_gas_sf6_pequeno": "AB22",
        "kit_llenado_sf6": "AB23",
        "kit_racores": "AB24",
        "pd_scan_descargas_parciales": "AB25",
        "camara_termografica_nec": "AB26",
        "camara_termografica_irys": "AB27",
        "fuentes_110_220v": "AB29",
        "secuencimetro": "AB28"
    }
    