# Generated by Django 5.1 on 2024-09-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mtto_equipos_de_computo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerequipmentmaintenance',
            name='computer_equipment_id',
            field=models.CharField(default='COM-', max_length=100),
        ),
    ]
