# Generated by Django 3.2.25 on 2024-05-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Process_Project', models.CharField(max_length=100)),
                ('Date_of_application', models.DateField()),
                ('Applicants_Position', models.CharField(max_length=100)),
            ],
        ),
    ]
