# Generated by Django 5.1 on 2024-08-16 14:52

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions_of_employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hired', models.CharField(max_length=4)),
                ('Type_of_Contract', models.CharField(max_length=100)),
                ('Overtime_Hours', models.CharField(max_length=4)),
                ('Duration_of_Engagement', models.DateField(default=datetime.date(2025, 8, 16))),
                ('Management_and_Trust', models.CharField(max_length=4)),
                ('Workplace', models.CharField(max_length=100)),
                ('Start_Date', models.DateField(default=django.utils.timezone.now)),
                ('Monday_to_Friday_start', models.TimeField(default=datetime.time(7, 0))),
                ('Monday_to_Friday_end', models.TimeField(default=datetime.time(17, 30))),
                ('Saturday_start', models.TimeField(default=datetime.time(7, 0))),
                ('Saturday_end', models.TimeField(default=datetime.time(11, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Data_of_selected_personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Identification_document', models.IntegerField()),
                ('Adress', models.CharField(max_length=100)),
                ('Phone_number', models.IntegerField(blank=True, null=True)),
                ('Movile_number', models.IntegerField()),
                ('Current_HIP', models.CharField(max_length=100)),
                ('AFP', models.CharField(max_length=100)),
                ('RH', models.CharField(max_length=3)),
                ('Allergies', models.CharField(blank=True, max_length=100, null=True)),
                ('Yellow_fever', models.CharField(max_length=100)),
                ('Tetanus', models.CharField(max_length=100)),
                ('Medical_examination', models.CharField(max_length=100)),
                ('Does_the_applicant_meet_the_job_profile', models.CharField(max_length=100)),
                ('Pants', models.IntegerField()),
                ('Shirt', models.CharField(max_length=2)),
                ('Shoes', models.IntegerField()),
                ('Overall', models.CharField(max_length=2)),
                ('Observations', models.TextField(blank=True, null=True)),
                ('Work_References', models.TextField(blank=True, null=True)),
                ('Personal_References', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Process_Project', models.CharField(max_length=100)),
                ('Date_of_application', models.DateField(default=django.utils.timezone.now)),
                ('Applicants_Position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salary_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic_salary', models.IntegerField()),
                ('Transportation_Allowance', models.CharField(max_length=4)),
                ('Value_Transportation_Allowance', models.IntegerField(blank=True, null=True)),
                ('Bonus', models.IntegerField(blank=True, null=True)),
                ('Travel_Allowance', models.CharField(max_length=4)),
                ('Value_Travel_Allowance', models.IntegerField(blank=True, null=True)),
                ('Other', models.CharField(max_length=4)),
                ('Which', models.CharField(blank=True, max_length=100, null=True)),
                ('Observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(max_length=100)),
                ('Which', models.CharField(blank=True, max_length=250, null=True)),
                ('Name_of_the_Position_Requested', models.CharField(max_length=100)),
                ('Job_Profile', models.CharField(max_length=100)),
            ],
        ),
    ]
