# Generated by Django 5.1 on 2024-08-21 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Duration_of_Engagement',
            field=models.DateField(default=datetime.date(2025, 8, 21)),
        ),
    ]
