# Generated by Django 3.2.25 on 2024-05-09 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_Position', models.CharField(max_length=2)),
                ('Temporary', models.CharField(max_length=2)),
                ('New_Project', models.CharField(max_length=2)),
                ('Other', models.CharField(max_length=2)),
                ('Which', models.CharField(max_length=250)),
                ('Name_of_the_Position_Requested', models.CharField(max_length=100)),
                ('Job_Profile', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='Date_of_application',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
