# Generated by Django 3.2.25 on 2024-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0002_auto_20240509_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_requisition',
            name='New_Position',
        ),
        migrations.RemoveField(
            model_name='staff_requisition',
            name='New_Project',
        ),
        migrations.RemoveField(
            model_name='staff_requisition',
            name='Other',
        ),
        migrations.RemoveField(
            model_name='staff_requisition',
            name='Temporary',
        ),
        migrations.AddField(
            model_name='staff_requisition',
            name='Reason',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
