# Generated by Django 3.2.25 on 2024-05-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0007_rename_human_resources_data_of_selected_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Monday_to_Friday_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Monday_to_Friday_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Saturday_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Saturday_start',
            field=models.TimeField(),
        ),
    ]
