# Generated by Django 3.2.25 on 2024-05-15 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0009_auto_20240515_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Hired',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Management_and_Trust',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Monday_to_Friday_end',
            field=models.TimeField(default=datetime.time(17, 30)),
        ),
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Overtime_Hours',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Saturday_end',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
