# Generated by Django 3.2.25 on 2024-05-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0010_auto_20240515_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic_salary', models.IntegerField()),
                ('Transportation_Allowance', models.IntegerField()),
                ('Bonus', models.IntegerField()),
                ('Travel_Allowance', models.IntegerField()),
                ('Other', models.IntegerField()),
            ],
        ),
    ]
