# Generated by Django 3.2.25 on 2024-05-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0011_salary_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_assignment',
            name='Other',
            field=models.CharField(max_length=100),
        ),
    ]
