# Generated by Django 3.2.25 on 2024-05-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0012_alter_salary_assignment_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_assignment',
            name='Value_Transportation_Allowance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary_assignment',
            name='Value_Travel_Allowance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary_assignment',
            name='Which',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary_assignment',
            name='Other',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='salary_assignment',
            name='Transportation_Allowance',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='salary_assignment',
            name='Travel_Allowance',
            field=models.CharField(max_length=4),
        ),
    ]
