# Generated by Django 3.2.25 on 2024-05-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0013_auto_20240515_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_assignment',
            name='Bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary_assignment',
            name='Value_Transportation_Allowance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary_assignment',
            name='Value_Travel_Allowance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
