# Generated by Django 3.2.25 on 2024-05-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0014_auto_20240515_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_assignment',
            name='Which',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
