# Generated by Django 3.2.25 on 2024-05-16 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPV_app', '0015_alter_salary_assignment_which'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_assignment',
            name='Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conditions_of_employment',
            name='Duration_of_Engagement',
            field=models.DateField(default=datetime.date(2025, 5, 16)),
        ),
    ]
