# Generated by Django 3.2.25 on 2024-05-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoja_de_vida_vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_data',
            name='Chassis_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='general_data',
            name='Engine_number',
            field=models.CharField(max_length=50),
        ),
    ]
