# Generated by Django 3.2.25 on 2024-05-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoja_de_vida_vehiculo', '0002_auto_20240527_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docments',
            name='Tecno_mechanical',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docments',
            name='Validity_SOAT',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docments',
            name='Vality_Inssurance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
