# Generated by Django 3.2.25 on 2024-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoja_de_vida_vehiculo', '0003_auto_20240528_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docments',
            name='Front_phioto',
        ),
        migrations.AddField(
            model_name='docments',
            name='Front_photo',
            field=models.ImageField(default=None, upload_to='photos_vehicle/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docments',
            name='Side_photo',
            field=models.ImageField(upload_to='photos_vehicle/'),
        ),
    ]
