# Generated by Django 3.2.25 on 2024-05-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoja_de_vida_vehiculo', '0005_alter_docments_policy_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnical_specifications',
            name='General_obsecatios',
        ),
        migrations.AddField(
            model_name='tecnical_specifications',
            name='General_observatios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
