# Generated by Django 3.2.25 on 2024-05-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hoja_de_vida_vehiculo', '0007_auto_20240530_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='docments',
            name='id_License_plate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hoja_de_vida_vehiculo.general_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnical_specifications',
            name='id_License_plate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hoja_de_vida_vehiculo.general_data'),
            preserve_default=False,
        ),
    ]
