# Generated by Django 3.2.25 on 2024-06-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoja_de_vida_vehiculo', '0008_auto_20240530_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnical_specifications',
            name='Load_capacity',
            field=models.CharField(max_length=100),
        ),
    ]
